import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Awsome Site!",
  description: "Generated by create next app + Sanity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  );
}
